- models/roomModel.js
- Define a Mongoose schema for the Room model with fields: id (UUID), room_type (with enum), room_number, price, status (with enum).
- Include reference to the Hotel model and an array of amenities.
- Enforce field constraints such as required fields, min values, and default values.
- Export the Room model for reuse.
> Add Room schema and model using Mongoose

- models/reviewModel.js
- Define a Mongoose schema for the Review model with fields: id (UUID), rating (1-5), description (max 200 characters).
- Include references to the User and Hotel models.
- Enforce field constraints such as required fields, min/max values.
- Export the Review model for reuse.
> Add Review schema and model using Mongoose

- models/locationModel.js
- Define a Mongoose schema for the Location model with fields: id (UUID), country, city, address, zip_code.
- Enforce field constraints such as required fields and maxlength values.
- Export the Location model for reuse.
> Add Location schema and model using Mongoose

- models/hotelModel.js
- Define a Mongoose schema for the Hotel model with fields: id (UUID), name, property_type, star_rating, num_rooms, images.
- Include a reference to the Location model.
- Enforce field constraints such as required fields, min/max values.
- Export the Hotel model for reuse.
> Add Hotel schema and model using Mongoose

- models/discountModel.js
- Define a Mongoose schema for the Discount model with fields:
id (UUID), code, discount, start_date, end_date, status (enum).
- Add a virtual field `is_active` to check the discount's active status based on dates.
- Enforce field constraints such as required fields, maxlength values, and enum.
- Export the Discount model for reuse.
> Add Discount schema and model using Mongoose

- models/bookingModel.js
- Define a Mongoose schema for the Booking model with fields: id (UUID), check_in, check_out, total_price, status (enum).
- Include references to the User, Hotel, Room, and Discount models.
- Enforce field constraints such as required fields and enum values.
- Export the Booking model for reuse.
> Add Booking schema and model using Mongoose

- models/ameniyModel.js
- Define a Mongoose schema for the Amenity model with fields: id (UUID), name, description.
- Enforce field constraints such as required fields and maxlength values.
- Export the Amenity model for reuse.
> Add Amenity schema and model using Mongoose

- controllers/discountController.js
- Implement `getDiscounts` to fetch all discounts from the database.
- Handle cases where no discounts are found by throwing a 404 error.
- Return the discounts as a JSON response with a 200 status code.
> Add controller function to retrieve discounts

- controllers/discountController.js
- Implement `getDiscount` to fetch a discount by its ID from the database.
- Handle cases where no discount is found by throwing a 404 error.
- Return the discount as a JSON response with a 200 status code.
> Add controller function to retrieve a single discount by ID

- controllers/discountController.js
- Implement `createDiscount` to create and save a new discount in the database.
- Validate required fields (`code`, `discount`, `start_date`, and `end_date`) and handle missing fields with a 400 error.
- Return the newly created discount as a JSON response with a 201 status code.
> Add controller function to create a new discount

- controllers/discountController.js
- Implement `updateDiscount` to allow updates to discount fields (`code`, `discount`, `start_date`, `end_date`, `status`).
- Validate that at least one field is provided for update and ensure no fields are empty.
- Use `findByIdAndUpdate` with options to return the updated document and enforce schema validators.
- Return the updated discount as a JSON response with a 200 status code.
- Handle errors for missing fields, invalid ID, and other unexpected issues.
> Add controller function to update an existing discount

- controllers/discountController.js
- Implement `deleteDiscount` to delete a discount from the database using its ID.
- Handle the case where no discount is found by returning a 404 error.
- Return the deleted discount as a JSON response with a 200 status code.
> Add controller function to delete a discount by ID

- controllers/bookingController.js
- Implement `getBookings` to retrieve all bookings from the database, with populated fields for user, hotel, room, and discount.
- Return the bookings as a JSON response with a 200 status code.
- Handle the case where no bookings are found by returning a 404 error.
> Add controller function to get all bookings

- controllers/bookingController.js
- Implement `getBooking` to retrieve a single booking by ID, with populated fields for user, hotel, room, and discount.
- Return the booking as a JSON response with a 200 status code.
- Handle the case where no booking is found by returning a 404 error.
> Add controller function to get booking by ID

- controllers/bookingController.js
- Implement `createBooking` to create a new booking with check-in, check-out, total price, status, user, hotel, room, and discount.
- Validate that all required fields are provided before saving the booking.
- Return the saved booking as a JSON response with a 201 status code.
- Handle errors and return appropriate messages if any required fields are missing or other issues occur.
> Add controller function to create a booking

- controllers/bookingController.js
- Implement `updateBooking` to update booking details with provided check-in, check-out, total price, status, user, hotel, room, and discount.
- Ensure that at least one field is provided for update, and validate that the fields are not empty.
- Use `findByIdAndUpdate` to apply updates and return the updated booking.
- Return appropriate error messages if no booking is found or if required fields are missing.
> Add controller function to update a booking

- controllers/amenityController.js
- Implement `getAmenities` to retrieve all amenities from the database.
- Return a 404 error if no amenities are found.
- Populate hotel amenities related data while retrieving amenities.
- Added detailed JSDoc comment to the `getAmenities` function.
- Described route, access, expected responses, and error handling.
- Explained the use of `populate` for fetching related hotel amenities.
> Add controller function to get all amenities

- controllers/amenityController.js
- Implement `createAmenity` to handle new amenity creation.
- Validate required fields: `name`, `description`, and `hotel_amenities`.
- Save new amenity and return the created amenity object.
> Add controller function to create a new amenity 

- controllers/amenityController.js
- Implement `updateAmenity` to handle updating existing amenity fields.
- Validate updated fields and ensure they are not empty.
- Return the updated amenity or an error if update fails.
> Add controller function to update an amenity

- controllers/amenityController.js
- Implement `deleteAmenity` to handle removal of an amenity by ID.
- Return a success message upon successful deletion or throw an error if amenity is not found.
> Add controller function to delete an amenity

- routes/discountRoute.js
- Define routes for managing discount resources:
- `GET /api/discounts`: Retrieve all discounts.
- `GET /api/discounts/:id`: Retrieve a discount by its ID.
- `POST /api/discounts`: Create a new discount.
- `PUT /api/discounts/:id`: Update an existing discount.
- `DELETE /api/discounts/:id`: Delete a discount by its ID.
- Add documentation for each route with parameters, access levels, and responses.
- Routes use corresponding controller functions for each operation.
> Implement discount routes with CRUD operations

- routes/bookingRoute.js
- Define routes for managing booking resources:
- `GET /api/bookings`: Retrieve all bookings.
- `GET /api/bookings/:id`: Retrieve a booking by its ID.
- `POST /api/bookings`: Create a new booking.
- `PUT /api/bookings/:id`: Update an existing booking.
- `DELETE /api/bookings/:id`: Delete a booking by its ID.
- Routes map to corresponding controller functions for each operation.
> Implement booking routes with CRUD operations

- routes/amenityRoute.js
- Define routes for managing amenity resources:
- `GET /api/amenities`: Retrieve all amenities.
- `GET /api/amenities/:id`: Retrieve a specific amenity by its ID.
- `POST /api/amenities`: Create a new amenity.
- `PUT /api/amenities/:id`: Update an existing amenity.
- `DELETE /api/amenities/:id`: Delete an amenity by its ID.
- Routes map to corresponding controller functions for each operation.;
> Implement amenity routes with CRUD operations

- .eslintrc.js
- .eslintrc.json
- .gitignore
- babel.config.js
- eslint.config.mjs
- package-lock.json
- package.json
- Added `.eslintrc.js` and `.eslintrc.json` for ESLint configuration.
- Included `babel.config.js` for Babel setup.
- Updated `.gitignore` to exclude unnecessary files from Git tracking.
- Added `eslint.config.mjs` for ESLint module configuration.
- Committed `package-lock.json` and `package.json` to reflect the current dependencies and configurations.
These changes establish the necessary configurations for linting, Babel transpilation, and project dependency management.
> Add configuration files for ESLint, Babel, and Git

- config/db.js
- Implemented `connectDB` function to establish a connection to MongoDB using Mongoose.
- Configured connection strings for both local and cloud (MongoDB Atlas) environments.
- Integrated environment variables (`DB_USERNAME` and `DB_PASSWORD`) for secure credentials handling.
- Fallback connection string for local MongoDB included if credentials are not provided.
- Enhanced error handling for database connection failures.
This setup allows flexible MongoDB connections and supports local development as well as production deployment.
> Add MongoDB connection setup with Mongoose

- middleware/errorHandler.js
- Implemented `errorHandler` middleware to standardize error responses across the application.
- Logs error stack traces to the console for debugging.
- Ensures proper status codes are returned in the response (defaulting to 500 for server errors).
- Provides a consistent JSON error response format with the error message.
This middleware enhances error management and improves debugging and user feedback.
> Add centralized error handling middleware

- server.js
- Initialized Express app and configured middleware to handle JSON requests and errors.
- Integrated environment variable loading with `dotenv` for secure configuration management.
- Connected to MongoDB using the `connectDB` function.
- Defined routes for `discounts`, `bookings`, and `amenities`, mapped to corresponding controllers.
- Set up a simple "Hello" route for testing purposes.
- Configured custom error handler to manage errors consistently throughout the app.
This setup ensures clean routing, centralized error handling, and database connectivity for the application.
> Setup Express application with routes and error handling

- controllers/discountController.js
- Added functions for managing discounts, including `getDiscounts`, `getDiscount`, `createDiscount`, `updateDiscount`, `deleteDiscount`, and `incrementDiscountUsage`.
- Introduced logic to handle discount creation and updating, with validation to ensure required fields are present.
- Implemented `updateDiscountStatuses` to automatically deactivate expired discounts.
- Created `checkDiscountActiveOrInactive` to verify whether a discount is active or expired before use.
- Enhanced error handling by throwing descriptive error messages for various discount-related operations (e.g., discount not found, invalid discount status).
- Ensured consistent error handling using `next(error)` in all functions for centralized error management.
This commit improves the discount management functionality, …
> feat: Implement discount management functions and enhance error handling

- controllers/bookingController.js
- Integrated `checkDiscountActiveOrInactive` and `incrementDiscountUsage` in both `createBooking` and `updateBooking` functions to ensure discounts are valid and usage is incremented upon booking creation and updates.
- Implemented discount validation and usage increment logic for the `discount` field to ensure proper discount handling and avoid expired or overused discounts.
- Improved the booking creation and update process by adding discount validation checks before saving or updating bookings.
This update ensures proper discount management, preventing invalid or expired discounts from being applied to bookings.
> feat: Add discount validation and usage increment to booking operations

- config/db.js
- Introduced command-line arguments to provide a username and password for MongoDB connection.
- Set the `USERNAME` and `PASSWORD` environment variables based on provided arguments.
- Configured `MONGO_URI` to switch between default MongoDB connection and MongoDB Atlas connection, depending on the presence of username and password.
- Added error handling to ensure both username and password are provided.
This update allows for flexible MongoDB URI configuration based on environment variables or provided credentials.
> feat: Add environment-based MongoDB URI configuration

- server.js
- Implemented a cron job to update discount statuses every hour using the `cron.schedule` function.
- Added a commented-out version using `setInterval` for running the update every 5 seconds (for testing purposes).
- Ensured that the scheduled job logs when it runs and calls the `updateDiscountStatuses` function.
This update introduces a regular task to update discount statuses at fixed intervals, improving the management of discount data.
> feat: Add scheduled jobs for updating discount statuses

- models/discountModel.js
- Added `usedCount` field to track the number of times a discount has been used, with a default value of `0`.
- Added `maxUse` field to specify the maximum allowed usage of a discount, marked as required.
- These fields are crucial for managing and enforcing discount usage limits.
This update allows for better tracking and control over discount usage and limits.
> feat: Add discount usage tracking fields

- controllers/bookingController.js
- Implemented `calculateTotalPrice` function to compute the total price based on the selected room and stay duration.
- Added checks for valid room, check-in and check-out dates.
- Ensured the check-out date is later than the check-in date, and calculated the number of nights for price calculation.
- Handled errors for invalid room, dates, or price calculation logic.
This commit adds functionality for dynamic price calculation based on room selection and stay duration.
> feat: Add total price calculation logic based on room and dates

- controllers/bookingController.js
- Updated all booking-related route handlers (`getBookings`, `getBooking`, `createBooking`, `updateBooking`, `deleteBooking`) to provide consistent and detailed JSON responses.
- Added success and message fields to API responses for better clarity.
- Improved API documentation for each route, specifying request/response formats, parameters, and potential error cases.
- Ensured that all routes are properly handling errors and returning appropriate HTTP status codes.
> Enhance API response and documentation

- tests/userTest/userController_DELETE.test.js
- Added Jest tests for the `deleteUser` function to cover various scenarios.
- Tested scenarios where the user is not found, user is successfully deleted, and unexpected errors occur.
- Mocked `User.findByIdAndDelete` to simulate different outcomes.
This commit ensures proper testing of the `deleteUser` functionality, improving test coverage and reliability.
> test: Add unit tests for deleteUser function

- tests/userTest/userController_GET.test.js
- Added Jest tests for the `getUsers` function to cover different scenarios.
- Tested cases where no users are found, users are successfully retrieved, and unexpected errors occur.
- Mocked `User.find` method to simulate different outcomes for database queries.
This commit improves test coverage for the `getUsers` function, ensuring proper error handling and response behavior.
> test: Add unit tests for getUsers function

- tests/userTest/userController_GET_BY_ID.test.js
- Added Jest tests for the `getUser` function to handle different scenarios.
- Tested cases where the user is not found, the user is successfully retrieved, and unexpected errors occur.
- Mocked `User.findById` method to simulate different outcomes for fetching user by ID.
This commit ensures proper handling of user retrieval and error scenarios for the `getUser` function.
> test: Add unit tests for getUser function

- tests/userTest/userController_POST.test.js
- Added Jest tests for the `createUser` function to handle various scenarios.
- Tested cases where required fields are missing, user is successfully created, and unexpected errors occur.
- Mocked `bcrypt.hash` for password hashing and `User.save` for saving the user to the database.
- Ensured proper error handling and response structure in `createUser`.
This commit ensures that the `createUser` function behaves as expected in different scenarios, including error handling and password encryption.
> test: Add unit tests for createUser function

- tests/userTest/userController_PUT.test.js
- Added Jest tests for the `updateUser` function to handle various scenarios.
- Tested cases where no fields are provided for update, user not found, successful update, and unexpected errors.
- Mocked `bcrypt.hash` for password hashing and `User.findByIdAndUpdate` for updating the user in the database.
- Ensured proper error handling and response structure in `updateUser`.
This commit ensures that the `updateUser` function behaves as expected in different scenarios, including error handling and password encryption.
> test: Add unit tests for updateUser function

- tests/discountTest/discountController_checkDiscountActiveOrInactive.test.js
- Added Jest tests for the `checkDiscountActiveOrInactive` function to handle different scenarios.
- Tested cases where the discount is not found, expired (inactive status), active, and handling of unexpected errors.
- Mocked `Discount.findById` to simulate database responses and verified correct error handling and logging.
- Ensured that the function behaves correctly for active discounts and handles exceptions properly.
This commit ensures that the `checkDiscountActiveOrInactive` function works as expected for various discount statuses.
> test: Add unit tests for checkDiscountActiveOrInactive function

- tests/discountTest/discountController_GET_BY_ID.test.js
- Added Jest tests for the `getDiscount` function to handle scenarios where no discount is found and where a valid discount is returned.
- Mocked `Discount.findById` to simulate the retrieval of a discount from the database.
- Verified that a 404 error is returned when no discount is found and a 200 status is returned with the discount data when a valid ID is provided.
- Ensured proper error handling by testing that the `next` middleware is called with an error when no discount is found.
This commit ensures that the `getDiscount` function is thoroughly tested.
> test: Add unit tests for getDiscount controller function

- tests/discountTest/discountController_incrementDiscountUsage.test.js
- Added Jest tests for the `incrementDiscountUsage` function to handle different discount usage scenarios.
- Included tests for situations where the discount is not found, has reached its maximum usage, and successfully increments usage while checking for maximum usage.
- Validated that the status is updated to "Inactive" when the maximum usage is reached and the usage is incremented when it is less than the maximum.
- Handled unexpected errors by mocking database errors and ensuring proper error handling.
This commit ensures comprehensive testing for the `incrementDiscountUsage` function.
> test: Add unit tests for incrementDiscountUsage function

- tests/discountTest/discountController_POST.test.js
- Added Jest tests for the `createDiscount` controller to validate various scenarios such as missing required fields, invalid date ranges, and invalid discount values.
- Included tests for successful creation of a discount with proper status codes and response data.
- Ensured the function handles unexpected errors gracefully and returns a 500 status.
- Mocked `Discount` model to test the controller logic effectively.
This commit ensures comprehensive testing for the `createDiscount` function, ensuring robust error handling and correct response generation.
> test: Add unit tests for createDiscount controller

- tests/discountTest/discountController_PUT.test.js
- Added Jest tests for the `updateDiscount` controller to cover various scenarios such as missing fields, empty required fields, and non-existent discount IDs.
- Included tests for successful discount updates and the proper return of status codes and response data.
- Ensured the function handles unexpected errors correctly, passing them to the next middleware for proper error handling.
- Mocked `findByIdAndUpdate` method to effectively test controller logic.
This commit ensures robust testing for the `updateDiscount` function, including validation, error handling, and successful updates.
> test: Add unit tests for updateDiscount controller

- tests/discountTest/discountController_updateDiscountStatuses.test.js
test: Add unit tests for updateDiscountStatuses function
- Added Jest tests for the `updateDiscountStatuses` function to cover various scenarios such as no active discounts, updates to discount statuses based on expiry, and error handling.
- Mocked `Discount.find` method to simulate database interactions and ensure proper testing of the function's logic.
- Included tests to ensure that expired discounts are marked as inactive and active discounts remain unchanged.
- Verified that the function logs the correct output messages and handles unexpected errors appropriately.
This commit ensures comprehensive testing for the `updateDiscountStatuses` function, covering typical and edge cases.
> test: Add unit tests for updateDiscountStatuses function

- tests/bookingTest/bookingController_POST.test.js
- Implemented Jest tests for the `createBooking` controller, covering:
- Case where required fields are missing, returning a 400 error.
- Successful booking creation when all required fields are provided, returning a 200 status with booking details.
- Mocked the `Booking` model to simulate database operations and integrated `discountController` functions for handling discounts.
These tests ensure the `createBooking` controller handles both successful and error scenarios properly.
> test: Add unit tests for createBooking controller

- tests/bookingTest/bookingController_DELETE.test.js
- Implemented Jest tests for the `deleteBooking` controller, covering:
- Validation error when the booking ID is not found.
- Successful deletion of a booking, returning the deleted booking details.
- Mocked `Booking` model to simulate database operations.
These tests ensure robust validation, error handling, and functionality for the `deleteBooking` controller.
> test: Add unit tests for deleteBooking controller

- tests/bookingTest/bookingController_calculateTotalPrice.test.js
- Implemented Jest tests for the `calculateTotalPrice` function, covering:
- Validation errors for invalid room ID, check-in, and check-out dates.
- Ensuring the check-out date is greater than the check-in date.
- Correct calculation of the total price based on room price and number of nights.
- Handling unexpected errors gracefully by throwing them.
- Mocked `Room` model to simulate database operations.
This commit ensures comprehensive validation, error handling, and pricing logic for the `calculateTotalPrice` function.
> test: Add unit tests for calculateTotalPrice function

- tests/bookingTest/bookingController_PUT.test.js
- Implemented Jest tests for the `updateBooking` controller, covering:
- Case where no fields are provided for the update, returning a 400 error.
- Case where a required field is empty, returning a 400 error.
- Case where no booking is found by the provided ID, returning a 404 error.
- Successful booking update, including the use of the `calculateTotalPrice` function to update the total price, returning a 200 status with updated booking details.
- Mocked the `Booking` model to simulate database operations and integrated `calculateTotalPrice` function for calculating updated prices.
These tests ensure the `updateBooking` controller handles both successful and error scenarios properly.
> test: Add unit tests for updateBooking controller

- tests/roomTest/roomController_PUT.test.js
- Implemented Jest tests for the `updateRoom` controller, covering:
- Case where required fields (`room_type`, `room_number`, `price`, `status`, `hotel`, and `amenities`) are missing, returning a 404 error with a respective message.
- Successful room creation when all required fields are provided, returning a 201 status with the created room data.
- Handling unexpected errors and forwarding them to the next middleware.
- Mocked the `Room` model to simulate database operations, ensuring the controller works as expected in both success and error scenarios.
These tests ensure the `updateRoom` controller correctly handles missing fields and processes room creation requests efficiently.
> test: Add unit tests for updateRoom controller

- controllers/bookingController.js
- Added `.exec()` to the `Booking.findById()` query to handle promises more efficiently.
- Updated 404 error response to return a structured JSON message when booking is not found.
- Improved success response format with a success flag, message, and data.
> Refactor getBooking endpoint: Use .exec() and improve response structure

- controllers/bookingController.js
- Added `.exec()` to the `Booking.find()` query for better handling of promises.
- Updated the 404 error response to return a structured JSON message with a custom error message.
- Improved the success response format with a success flag, message, and data.
- Enhanced the check for empty bookings by verifying the array length.
> Refactor getBookings endpoint: Use .exec() and improve error handling

- controllers/bookingController.js
Added a utility function to calculate the total price after applying a discount. The function retrieves the discount details from the database using the discount ID, validates its existence, and computes the discounted price. Includes robust error handling for invalid discount IDs and database errors.
> feat: Implement calculate_total_price_after_discount function

- controllers/discountController.js
Updated the `getDiscounts` function to include logic for filtering discounts with valid start and end dates. Added a validation check to ensure the start date is earlier than or equal to the end date. Improved error handling for cases where no valid discounts are found.
> refactor: Enhance getDiscounts to filter valid discounts

- controllers/hotelController.js
- Retrieves a list of hotels based on a given location ID.
- Populates hotel reviews for enhanced response details.
- Implements error handling for locations with no available hotels.
- Sends a structured success response with hotel data.
> feat: Add getHotelsFromLocation function to fetch hotels by location

- controllers/locationController.js
- Corrected logic to check if locations array is empty in the getLocations function.
- Provides more accurate error message when no locations are found.
> fix: Improve getLocations error handling for empty location arrays

- controllers/paymentController.js
- Integrated Stripe checkout session for booking payment processing.
- Added validation for booking dates and room details.
- Returns checkout session URL for successful payment redirection.
> feat: Implement Stripe checkout for booking payment

- controllers/amenityController.js
- Removed `hotel_amenities` field from `createAmenity` and `updateAmenity` methods for simplicity.
- Adjusted validation to require only `name` and `description` fields.
- Updated documentation to reflect the changes in route behavior.
- Improved code readability and error handling consistency across methods.
> feat: Update Amenity routes for simplified structure

- controllers/hotelController.js
- Removed unnecessary `review` population in the `getHotels` and `getHotel` functions for optimized performance.
- Updated `getHotel` to only populate `location` and `rooms`, removing `review` population.
- Simplified the `getHotels` function to only populate `location`, improving efficiency.
> Refactor getHotels and getHotel controllers:

- controllers/bookingController.js
- Removed redundant population of 'discount' field in GET and POST routes.
- Simplified booking creation by removing unused 'status' field in POST route.
- Ensured that the booking is created with the correct total price, considering optional discounts.
- Optimized error handling and validation for required fields in booking creation.
> Refactor booking controller:

- controllers/roomController.js
- Integrated the `getPagination` utility function into the `getRooms` endpoint.
- Pagination logic now handles `page`, `limit`, and `skip` query parameters for room data.
- Returns paginated results for rooms, including total count, total pages, and associated data (hotel, amenities).
- Added error handling for empty room results.
This update ensures efficient retrieval of room data with pagination support.
> feat: add pagination to getRooms endpoint

- controllers/locationController.js
- Integrated the `getPagination` utility function into the `getLocations` endpoint.
- Pagination logic now handles `page`, `limit`, and `skip` query parameters for location data.
- Returns paginated results for locations, including total count and total pages.
- Added error handling for empty location results.
This update ensures efficient retrieval of location data with pagination support.
> feat: add pagination to getLocations endpoint

- controllers/hotelController.js
- Integrated the `getPagination` utility function into the `getHotels` endpoint.
- Pagination logic now handles `page`, `limit`, and `skip` query parameters for hotel data.
- Returns paginated results for hotels, including total count and total pages.
- Added error handling for empty hotel results.
This update ensures efficient retrieval of hotel data with pagination support.
> feat: add pagination to getHotels endpoint

- .env.example
- config/db.js
- config/redisConfig.js
- config/swaggerConfig.js
- package.json
- server.js
- vercel.json
**Added vercel.json:**
1.   Configured for seamless deployment on Vercel.
**Updated swaggerConfig:**
1. Adjusted configurations to improve Swagger UI functionality.
2. Added a new route to serve Swagger documentation at /swagger.json.
**Updated redisConfig:**
1. Configured Redis to use Redis Cloud instead of a local Redis instance for caching.
**Modified server.js:**
1. Added middleware to support Swagger UI.
2. Introduced new routes to test and display Swagger documentation.
**Updated package.json:**
1. Added new dependencies required for the changes.
**Update .env.example**
1.Added new keys foe .env.example with placeholder and comments
> Deploy Bookify Application on Vercel with Enhanced Configuration

- tests/discountTest/discountController_updateDiscountStatuses.test.js
Added updateDiscountStatuses controller for bulk discount status updates based on end_date. Integrated detailed logging for successful updates and error handling. Updated unit tests to validate correct status transitions, logging behavior, and error scenarios. Replaced findByIdAndUpdate with find to support multiple record updates.
> feat: Implement bulk discount status update with enhanced logging

- tests/locationTest/locationController_GET.test.js
Replaced find with findById in getLocation controller for single location retrieval. Integrated Redis caching to return cached location data when available. Added mock for Redis get and setEx methods in unit tests. Ensured all tests cover caching, database retrieval, and proper mock clearing.
> feat: Enhance location retrieval with Redis caching

- tests/userTest/userController_GET.test.js
- Added Redis caching for the getUsers controller to return cached user data if available.
- Integrated pagination logic to handle page and limit query parameters for user retrieval.
- Mocked Redis, user model, and pagination utility for testing purposes.
- Updated test to verify Redis caching behavior and ensure pagination works correctly.
- Refined test to check if the user models find method is not called when data is fetched from Redis cache.
> Enhance getUsers controller with Redis caching and pagination support

- tests/userTest/userController_GET_BY_ID.test.js
- Updated the test for the `getUser` controller to focus on the successful retrieval of user data.
- Simplified the test by removing the 404 error handling and the user not found scenario.
- Mocked `User.findById` to return a mock user object with relevant fields.
- The test now checks for a successful 200 status response and ensures the user data is returned correctly.
> Refactor test for getUser to focus on user data retrieval

- tests/roomTest/roomController_DELETE.test.js
- Updated the success message in the `deleteRoom` response to return an object with a message instead of a string.
- Ensured consistency in error handling and testing logic for unexpected errors.
- Improved clarity in test cases to check the expected result more effectively.
> Refactor deleteRoom controller to improve success message response

- tests/reveiwTest/reviewController_GET_BY_ID.test.js
- Mock Redis client methods (get, setEx) for cache handling.
- Add test for returning cached review data if available.
- Modify tests to handle review retrieval from the database with Redis cache fallback.
- Implement afterEach hook to clear mocks after each test.
- Update error handling test for better exception management.
> Refactor getReview controller tests to integrate Redis caching

- tests/locationTest/locationController_PUT.test.js
- Removed redundant test case for successful location updates.
- Streamlined test suite to focus on error handling and edge cases:
- 400 error for missing or empty fields.
- 404 error when no location is found by the given ID.
- Handling unexpected errors and passing them to the next middleware.
- Enhanced test structure for better clarity and reusability.
> refactor: improve updateLocation controller tests

- controllers/amenityController.js
- Renamed `redisKey` to `cacheKey` for clarity in caching logic.
- Simplified the retrieval and caching of amenities with Redis by ensuring cache keys are consistent and concise.
- Updated `find()` method with `.exec()` for better query execution in `getAmenities` route.
- Improved condition checking for empty amenities array in the `getAmenities` route.
- Streamlined error handling and logging for Redis caching in both `getAmenities` and `getAmenity` routes.
- Removed redundant `console.log` statements in the `createAmenity` and `deleteAmenity` routes.
- Enhanced code readability and structure for better maintainability and consistency.
> Refactor amenities routes for caching and database operations
