youssef3092004/Portfolio-js

- models/bookingModel.js
- Removed the `status` field from the booking schema, including its default value and enum validation.
- Cleaned up unused code to streamline the schema.
This commit removes the status field from the booking schema, simplifying the data model.
> chore: Remove status field from booking schema

- tests/discountTest/discountController_GET.test.js
- Added Jest tests for the `getDiscounts` function to handle scenarios where no discounts are found, valid discounts are found, and invalid dates filter out discounts.
- Mocked `Discount.find` to simulate retrieving a list of discounts from the database.
- Verified that a 404 error is returned when no discounts or valid discounts are found.
- Ensured the filtering logic works correctly by testing that discounts with invalid date ranges are excluded and valid ones are returned.
- Validated that proper error handling is in place for unexpected outcomes.
This commit ensures comprehensive testing for the `getDiscounts` function.
> test: Add unit tests for getDiscounts controller function

- tests/locationTest/locationController_GET.test.js
- Added Jest tests for the `getLocations` controller to cover scenarios such as no locations found, successful location retrieval, and handling database errors.
- Mocked `Location.find` method to simulate database interactions for testing.
- Included tests to ensure proper response when no locations are found (404 error) and when locations are successfully retrieved (200 response).
- Added test case to simulate a database error and verify that it triggers proper error handling (500 response).
This commit ensures thorough testing of the `getLocations` controller, including handling edge cases and database interaction errors.
> test: Add unit tests for getLocations controller

- tests/locationTest/locationController_GET_BY_ID.test.js
- Added Jest tests for the `getLocation` controller, testing scenarios where the location is not found, found successfully, and when a database error occurs.
- Mocked `Location.findById` method to simulate database interactions.
- Ensured that the controller returns the correct HTTP status and error handling when the location is not found (404 error) or when a database error occurs (500 error).
- Verified that the correct location details are returned when found (200 status and location data).
This commit improves test coverage for the `getLocation` controller with edge case handling and proper response verification.
> test: Add unit tests for getLocation controller

- tests/locationTest/locationContrlloer_DELETE.test.js
- Added Jest tests for the `deleteLocation` controller to verify behavior in various scenarios:
- Returns a 404 error if the location is not found.
- Successfully deletes a location and returns a 200 status with the deleted location details.
- Handles unexpected errors by passing them to the next middleware.
- Mocked `Location.findByIdAndDelete` to simulate database interactions.
- Ensured proper error handling and response status codes for edge cases.
This commit enhances test coverage for the `deleteLocation` controller with robust error and success scenario validation.
> test: Add unit tests for deleteLocation controller

- tests/locationTest/locationController_POST.test.js
- Added Jest tests for the `createLocation` controller to validate various scenarios:
- Ensures appropriate error handling (status 404) when required fields (`country`, `city`, `address`, or `zip_code`) are missing.
- Successfully creates a location when all fields are provided and returns a 200 status with the saved location.
- Handles unexpected database errors and passes them to the next middleware with a 500 status.
- Mocked `Location.prototype.save` to simulate database operations.
- Ensured robust validation and error handling for edge cases.
This commit improves test coverage and ensures reliable behavior of the `createLocation` controller.
> test: Add unit tests for createLocation controller

- tests/locationTest/locationController_PUT.test.js
- Added Jest tests for the `updateLocation` controller, covering multiple scenarios:
- Ensures a 400 error is returned when no fields are provided for update.
- Validates handling of empty required fields with an appropriate 400 error.
- Handles a 404 error when no location is found by the given ID.
- Successfully updates a location when valid fields are provided, returning a 200 status and the updated location.
- Handles unexpected errors and passes them to the next middleware.
- Mocked `Location.findByIdAndUpdate` to simulate database operations.
- Improved error handling validation and test coverage.
This commit ensures the `updateLocation` controller is robust and reliable.
> test: Add unit tests for updateLocation controller

- tests/reveiwTest/reviewController_DELETE.test.js
- Added Jest unit tests for the `deleteReview` controller, including:
- Verifying a 404 error is returned when the review is not found.
- Ensuring a 200 status and the deleted review are returned when deletion is successful.
- Mocked `Review.findByIdAndDelete` for simulating database operations.
- Enhanced test coverage to validate error handling and success scenarios.
This commit ensures the reliability and robustness of the `deleteReview` controller.
> test: Add unit tests for deleteReview controller

- tests/reveiwTest/reviewController_GET_BY_ID.test.js
- Added Jest unit tests for the `getReview` controller, covering:
- A 404 response when no review is found by the given ID.
- A 200 response with the review data when a valid review is found.
- Error handling for unexpected errors, ensuring they are passed to the next middleware.
- Mocked `Review.findById` and its `populate` and `exec` methods to simulate database operations.
- Ensured tests verify proper responses and middleware behavior.
This commit improves the test coverage and reliability of the `getReview` controller.
> test: Add unit tests for getReview controller

- tests/reveiwTest/reviewController_GET.test.js
- Implemented Jest unit tests for the `getReviews` controller, including:
- A 404 response when no reviews are found.
- A 200 response with the list of reviews when reviews exist.
- Proper handling of unexpected errors, ensuring they are passed to the next middleware.
- Mocked `Review.find` with chained `populate` and `exec` methods to simulate database queries.
- Verified that the controller responds with the appropriate HTTP status codes and data.
This addition enhances the reliability and test coverage of the `getReviews` controller.
> test: Add unit tests for getReviews controller

- tests/reveiwTest/reviewController_POST.test.js
- Added Jest unit tests for the `createReview` controller, covering:
- A `404` error if any required field (rating, description, user, hotel) is missing.
- A `201` status and the created review when all fields are provided.
- Mocked `Review.save` to simulate saving the review to the database.
- Ensured tests validate proper error handling and successful review creation.
This commit improves the test coverage and reliability of the `createReview` controller.
> test: Add unit tests for createReview controller

- tests/bookingTest/bookingController_GET.test.js
- Implemented Jest tests for the `getBookings` controller, covering:
- Case where no bookings are found, returning a 404 error.
- Successful retrieval of multiple bookings, returning a 200 status with booking details.
- Mocked `Booking` model with chained `populate` and `exec` methods to simulate database queries.
These tests ensure proper handling of booking retrieval and error management for the `getBookings` controller.;
> test: Add unit tests for getBookings controller

- tests/bookingTest/bookingController_GET_BY_ID.test.js
- Implemented Jest tests for the `getBooking` controller, covering:
- Case where no booking is found by the given ID, returning a 404 error.
- Successful retrieval of a booking with populated details, returning a 200 status.
- Mocked `Booking` model with chained `populate` and `exec` methods to simulate database queries.
These tests ensure accurate functionality, error handling, and robust responses for the `getBooking` controller.
> test: Add unit tests for getBooking controller

- tests/roomTest/roomController_POST.test.js
- Implemented Jest tests for the `createRoom` controller, covering:
- Validation errors for missing required fields (`room_type`, `room_number`, `price`, `status`, `hotel`, `amenities`).
- A `201` status and returning the created room when all fields are provided.
- Mocked `Room` model to simulate database save operations.
This commit ensures robust validation and error handling for the `createRoom` controller.
> test: Add unit tests for createRoom controller

- tests/roomTest/roomController_GET_BY_ID.test.js
- Implemented Jest tests for the `getRoom` controller, covering:
- A `404` error when no room is found by the provided ID.
- A `200` status and returning the room details when the room is found.
- Mocked `Room.findById` with chaining for `.populate()` and `.exec()` methods to simulate database operations.
This commit enhances test coverage and verifies the proper handling of various scenarios in the `getRoom` controller.
> test: Add unit tests for getRoom controller

- tests/roomTest/roomController_GET.test.js
- Implemented Jest tests for the `getRooms` controller, covering:
- A `404` error when no rooms are available.
- A `200` status and returning the list of rooms when rooms are found.
- Mocked `Room.find` with chaining for `.populate()` and `.exec()` methods to simulate database queries.
This commit improves test coverage and ensures proper handling of various scenarios in the `getRooms` controller.
> test: Add unit tests for getRooms controller

- tests/roomTest/roomController_DELETE.test.js
- Added Jest unit tests for the `deleteRoom` controller, covering:
- A `404` error when the room is not found by the given ID.
- A `200` status and a success message when a room is successfully deleted.
- Mocked `Room.findByIdAndDelete` to simulate database operations.
- Ensured tests validate proper error handling, success responses, and middleware behavior.
This commit enhances the reliability and test coverage of the `deleteRoom` controller.
> test: Add unit tests for deleteRoom controller

- controllers/amenityController.js
- Removed `.populate("hotel_amenities")` from the Amenity query.
- Added check for an empty amenities array and return a 404 with a message if no amenities are found.
- Improved response format with a structured error message for better clarity.
> Refactor: getAmenities endpoint: Remove population of hotel_amenities

- controllers/amenityController.js
- Removed `.populate("hotel_amenities")` from the Amenity query.
- Modified the error response to return a structured message when no amenity is found.
- Updated the 404 error message to be more descriptive and clear.
> Refactor getAmenity endpoint: Simplify query and improve error handling

- tests/roomTest/roomController_GET.test.js
- Integrated Redis caching to optimize response times by fetching room data from the cache when available.
- Implemented pagination handling in the `getRooms` controller using query parameters (`page`, `limit`).
- Added cache key generation for pagination, ensuring cached data is specific to page and limit combinations.
- Mocked Redis and pagination utilities in tests to simulate cache hits and MongoDB queries.
- Improved error handling and tests to cover scenarios such as database errors and no rooms found.
- Used `setEx` to store MongoDB query results in Redis with a TTL of 1 hour.
> Enhance getRooms controller with Redis caching and pagination

- tests/roomTest/roomController_GET_BY_ID.test.js
- Implemented Redis caching in the `getRoom` controller to return cached room data if available, reducing database calls.
- Added `afterEach` cleanup to clear mocks after each test for better isolation and accuracy.
- Mocked Redis client methods (`get` and `setEx`) for testing Redis interactions.
- Ensured that the controller checks for cached data before querying the database.
- Improved test suite by verifying that Redis is queried first and the database is not called if data is cached.
> Enhance getRoom controller with Redis caching and cleanup

- tests/userTest/userController_PUT.test.js
- Removed password update from the successful update test case to focus on non-password fields.
- Updated test to verify the behavior when no password is provided in the request body.
- Adjusted mock for User.findByIdAndUpdate to return updated user without password.
- Kept the rest of the tests intact for checking error handling and the absence of provided fields.
> Refactor updateUser controller test to exclude password update

- tests/amenityTest/amenityController_DELETE_ALL.test.js
- Implemented tests for the deleteAllAmenitys controller in amenityController.
- Mocked Amenity.deleteMany to simulate deletion of amenities.
- Mocked Redis client to simulate cache deletion for amenities.
- Verified successful deletion and appropriate response messages.
- Added test for case when no amenities are found for deletion, returning a 404 error.
> Add tests for deleteAllAmenitys controller
